# Generated by Django 6.0.1 on 2026-01-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(help_text='Amount or Quantity donated'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Medicine', 'Medicine'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Medicine', 'Medicine'), ('Other', 'Other')], max_length=50),
        ),
    ]
