# Generated by Django 6.0.1 on 2026-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_donation_amount_alter_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('Money', 'Money'), ('Food', 'Food'), ('Clothes', 'Clothes'), ('Medicine', 'Medicine'), ('Other', 'Other')], max_length=20),
        ),
    ]
