# Generated by Django 6.0.1 on 2026-01-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beneficiary_details', models.CharField(max_length=200)),
                ('distribution_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Medicine', 'Medicine'), ('Other', 'Other')], max_length=50, unique=True)),
                ('available_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='distribution',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='mainapp.inventory'),
        ),
    ]
