# Generated by Django 6.0.1 on 2026-01-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_distribution_inventory_delete_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneySpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('spent_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='distribution_date',
            new_name='distributed_on',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.inventory'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='resource_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
